-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_omnimail_job_progress`;
DROP TABLE IF EXISTS `civicrm_mailing_provider_data`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_mailing_provider_data
-- *
-- * Data from the mailing provider
-- *
-- *******************************************************/
CREATE TABLE `civicrm_mailing_provider_data` (
  `contact_identifier` varchar(255) COMMENT 'External reference for the contact',
  `mailing_identifier` varchar(255) COMMENT 'External Reference for the mailing',
  `email` varchar(255) COMMENT 'Email Address',
  `event_type` varchar(255) COMMENT 'Type of action',
  `recipient_action_datetime` timestamp COMMENT 'When the action happened',
  `contact_id` int COMMENT 'Contact in CiviCRM',
  `is_civicrm_updated` tinyint COMMENT 'Has the action been synchronised through to CiviCRM',
  PRIMARY KEY (`contact_identifier`,`recipient_action_datetime`,`event_type`),
  CONSTRAINT FK_civicrm_mailing_provider_data_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`)
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_omnimail_job_progress
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_omnimail_job_progress` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique OmnimailJobProgress ID',
  `mailing_provider` varchar(512) COMMENT 'Mailing provider name',
  `job` varchar(32) COMMENT 'job name',
  `job_identifier` varchar(512) COMMENT 'optional suffix to disambiguate the job',
  `last_timestamp` timestamp COMMENT 'Mailing provider name',
  `progress_end_timestamp` timestamp COMMENT 'End timestamp of current retrieval',
  `retrieval_parameters` varchar(255) COMMENT 'json copy of any paramters that need to be passed to the provider.',
  `offset` int unsigned COMMENT 'How many lines have been processed',
  `created_date` timestamp COMMENT 'When was the job created',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;
